name: Testing on Windows
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '3.1', '2.7' ]
        os:
          - windows-latest
        include:
          - ruby: '3.0.3'
            os: windows-latest
            # On Ruby 3.0, we need to use fiddle 1.0.8 or later to retrieve correct
            # error code. In addition, we have to specify the path of fiddle by RUBYLIB
            # because RubyInstaller loads Ruby's bundled fiddle before initializing gem.
            # See also:
            # * https://github.com/ruby/fiddle/issues/72
            # * https://bugs.ruby-lang.org/issues/17813
            # * https://github.com/oneclick/rubyinstaller2/blob/8225034c22152d8195bc0aabc42a956c79d6c712/lib/ruby_installer/build/dll_directory.rb
            ruby-lib-opt: RUBYLIB=%RUNNER_TOOL_CACHE%/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/fiddle-1.1.0/lib

    name: Unit testing with Ruby ${{ matrix.ruby }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Add Fiddle 1.1.0
        if: ${{ matrix.ruby == '3.0.3' }}
        run: gem install fiddle --version 1.1.0
      - name: Install dependencies
        run: ridk exec bundle install --jobs 4 --retry 3
      - name: Run tests
        run: bundle exec rake spec ${{ matrix.ruby-lib-opt }}
